version: "3.9"

services:
  web:
    # Берем Dockerfile из каталога app
    image: marmunc/django_project:latest
    # Запускаем сервер gunicorn
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    # Открываем порт 8000 внутри и снаружи
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/django_project/web/static
      - media_volume:/home/app/django_project/web/media
    env_file:
      - ./.env.prod
    # Дожидаемся запуска контейнера db
    depends_on:
      - db
  db:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:15
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    image: marmunc/django_project:nginx
    volumes:
      - static_volume:/home/app/django_project/web/static
      - media_volume:/home/app/django_project/web/media
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  postgres_volume:
  static_volume:
  media_volume: